### ISSUE TITLE
Does not seem to work with current ETS2 anymore

### ISSUE THREAD

**Issue by schmic** [ncs-sniper/SII_Decrypt#1]
File gets decrypted but is not "cleartext" and not editable therefor.

**Comment by ncs-sniper** [comment]
The game is by-default saving data in binary format since few patches back. You have to edit game settings and reactivate saving to plaintext. Open **config.cfg** file (stored in your user folder, eg. _documents/Euro Truck Simulator 2/_) and change value **g_save_format** to 2.
I have some rudimentary knowledge of used binary format, but not enough to make a converter, sorry.

**Comment by schmic** [comment]
You might want to add that information into the README. Thanks.

**Comment by ncs-sniper** [comment]
Good idea, will do.

**Comment by schmic** [comment]
Just a heads up @ncs-sniper but there is no such property in my config.cfg, do I need to add it?

**Comment by schmic** [comment]
never mind, just found the right config.cfg
