### ISSUE TITLE
Use the lib in C#

### ISSUE THREAD

**Issue by Bluscream** [ncs-sniper/SII_Decrypt#3]
I would like to use the library in https://github.com/RayRay5/ets2_savegame_editor which is written in C#. Now i realized that this whole thing is written in Delphi. Is there a way i can use the lib anyway? Or do i have to invoke the cmdline binary?

**Comment by ncs-sniper** [comment]
SIIi Decrypt is also available as a DLL with flat C-style api (ie. only normal functions, no interfaces). This can be used from C# application, but you have to translate headers (https://github.com/ncs-sniper/SII_Decrypt/blob/master/Headers/SII_Decrypt_Header.pas) from pascal since I have too little experience with C# to write proper header. Just remember that you will be calling unmanaged code.

**Comment by Bluscream** [comment]
I'll probably stick with calling the cmd executable then :/ THanks anyway :)

**Comment by ncs-sniper** [comment]
Ok, let me know if you change your mind, I'll leave this open.

**Comment by ncs-sniper** [comment]
Since it is here for some time already, I think it is safe to assume not much will happen anymore. I am therefore closing this issue.
